version: '2'

services:
  dns:
    image: internetsystemsconsortium/bind9:9.16
    ports:
    - 53:53
    volumes:
      - volume1:/etc/bind
      - volume2:/var/cache/bind
      - volume3:/var/lib/bind
      - volume4:/var/log
volumes: 
    volume1:
    volume2:
    volume3:
    volume4:  